require "minitest/autorun"
require "webmock/minitest"
require "mocha/minitest"
require_relative "../lib/train-salt/connection"
require_relative "../lib/train-salt/errors"
require_relative "../lib/train-salt/transport"
