require "minitest/autorun"
require "webmock/minitest"
require_relative "../lib/train-salt/connection"
require_relative "../lib/train-salt/errors"
require_relative "../lib/train-salt/transport"
require_relative "../lib/train-salt/platform"
